#
# Ansible playbook for the ymir polyglot demo
#
- hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Push a template to the demo service
      template: src=templates/motd dest=/etc/motd mode="u=rw,g=r,o=r"
    - name: Install a system package
      package: pkg=tree state=installed update_cache=no
      register: apt_output
    - debug: var=apt_output # show the content of apt_output var
    - name: Push a file to the demo service
      copy: src=files/tmp_file dest=/tmp/ansible_tmp_file mode=0644

  # slow.  disable if possible!
  gather_facts: yes

  # no customization, so we might as well have used apt.
  # but, this is here to demonstrate the usage of roles
  roles:
    - { role: geerlingguy.nginx }
