#
# Ansible playbook for the ymir polyglot demo
#
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: puppet-bootstrap/debian.sh
      script: puppet-bootstrap/debian.sh
      when: ansible_distribution == 'Debian'
    - name: puppet-bootstrap/ubuntu.sh
      script: puppet-bootstrap/ubuntu.sh
      when: ansible_distribution == 'Ubuntu'
    - name: Install lsb-core for RedHat
      yum: name=redhat-lsb-core state=present
      when: ansible_os_family == "RedHat"
    - name: Reread ansible_lsb facts for RedHat
      setup: filter=ansible_lsb*
    - name: puppet-bootstrap/centos_6_x.sh
      script: puppet-bootstrap/centos_6_x.sh
      when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int < 7
    - name: puppet-bootstrap/centos_7_x.sh
      script: puppet-bootstrap/centos_7_x.sh
      when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 7
