#
# Ansible playbook for the ymir polyglot demo
#
- hosts: all
  become: yes
  become_method: sudo

  tasks:
    - script: puppet-bootstrap/debian.sh
      when: ansible_distribution == 'Debian'
    - script: puppet-bootstrap/ubuntu.sh
      when: ansible_distribution == 'Ubuntu'
    - yum: name=redhat-lsb-core state=present
      when: ansible_os_family == "RedHat"
    - name: Reread ansible_lsb facts for redhat
      setup: filter=ansible_lsb*
    - script: puppet-bootstrap/centos_6_x.sh
      when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int < 7
    - script: puppet-bootstrap/centos_7_x.sh
      when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 7

  # slow.  disable if possible!
  gather_facts: yes
